version: "3.10"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=database_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
       - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=database_name
      - POSTGRES_USER=database_user
      - POSTGRES_PASSWORD=database_password
    depends_on:
      - db


