# Generated by Django 4.1.7 on 2023-03-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boolpresures', '0002_bloodpressureparameters_pulse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressureparameters',
            name='examination_date',
            field=models.DateField(),
        ),
    ]
