# Generated by Django 4.1.7 on 2023-03-16 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boolpresures', '0003_alter_bloodpressureparameters_examination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressureparameters',
            name='examination_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
