# Generated by Django 4.1.7 on 2023-03-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boolpresures', '0004_alter_bloodpressureparameters_examination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressureparameters',
            name='pulse',
            field=models.IntegerField(),
        ),
    ]
