# Generated by Django 4.1.7 on 2023-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glucoses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucosesParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_level', models.IntegerField()),
                ('examination_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BloodPressureParameters',
        ),
    ]
