# Generated by Django 4.1.7 on 2023-03-16 11:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('glucoses', '0003_alter_glucosesparameters_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucosesparameters',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glucosesparameters',
            name='examination_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
